import { AiFillStar } from "react-icons/ai";

const data = [
  {
    id:1,
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/917nPCOw9-L._AC_UF894,1000_QL80_.jpg",
    title: "Galaxy S21 Ultrae",
    star: <AiFillStar className="rating-star" />,
    reviews: "Snapdragon",
    prevPrice: "$140,00",
    newPrice: "200",
    Size: "Android ",
    Native: "High-Res Display",
    category: "Smartphones",
  },
  {
    id:2,
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/71FpXTBHDnL.jpg",
    title: "Google Pixel 6 Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "Snapdragon",
    prevPrice: "$140,00",
    newPrice: "200",
    Size: "Android ",
    Native: "High-Res Display",
    category: "Smartphones",
  },

  {
    id:3,
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/612ytK4luvL._AC_UF894,1000_QL80_.jpg",
    title: "OnePlus 9 Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "Huawei",
    prevPrice: "$140,00",
    newPrice: "200",
    Size: "Android ",
    Native: "Multiple Cameras",
    category: "Smartphones",
  },
  {
    id:4,
    img: "https://img.scoop.it/JvpHfr2bJgnHvwZ0ZaX0yTl72eJkfbmt4t8yenImKBVvK0kTmF0xjctABnaLJIm9",
    title: "Xiaomi Mi 11",
    star: <AiFillStar className="rating-star" />,
    reviews: "Snapdragon",
    prevPrice: "$140,00",
    newPrice: "200",
    Size: "Android ",
    Native: "Dual SIM Support",
    category: "Tablets",
  },
  {
    id:5,
    img: "https://p3-ofp.static.pub/fes/cms/2022/09/28/zxv4vblinevcedidkpsih0ngvhhnow848907.png",
    title: "Sony Xperia 1 III",
    star: <AiFillStar className="rating-star" />,
    reviews: "Snapdragon",
    prevPrice: "$140,00",
    newPrice: "200",
    Size: "Android ",
    Native: "Fast Charging",
    category: "Tablets",
  },
  {
    id:6,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKvorxQnEL8mAIe9I5msq8YSeD560uSecWTw&usqp=CAU",
    title: "Huawei P40 Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "Huawei",
    prevPrice: "$140,00",
    newPrice: "50",
    Size: "Android ",
    Native: "High-Res Display",
    category: "Tablets",
  },

  {
    id:7,
    img: "https://images.fonearena.com/blog/wp-content/uploads/2020/05/Motorola-Edge-Plus-1024x843.jpg",
    title: "Motorola Edge+",
    star: <AiFillStar className="rating-star" />,
    reviews: "Snapdragon",
    prevPrice: "$140,00",
    newPrice: "50",
    Size: "Android ",
    Native: "Multiple Cameras",
    category: "Gaming Phones",
  },

  {
    id:8,
    img: "https://m.media-amazon.com/images/I/61Kl9gBo6LL.jpg",
    title: "LG Velvet",
    star: <AiFillStar className="rating-star" />,
    reviews: "Huawei",
    prevPrice: "$140,00",
    newPrice: "200",
    Size: "Android ",
    Native: "Long Battery Life",
    category: "Gaming Phones",
  },

  {
    id:9,
    img: "https://dlcdnwebimgs.asus.com/gain/7E04DF02-69CB-4425-A15E-A509A3C61220/w1000/h732",
    title: "Asus ROG Phone 5",
    star: <AiFillStar className="rating-star" />,
    reviews: "Snapdragon",
    prevPrice: "$140,00",
    newPrice: "200",
    Size: "Android ",
    Native: "Long Battery Life",
    category: "Gaming Phones",
  },

  {
    id:10,
    img: "https://akm-img-a-in.tosshub.com/sites/visualstory/stories/2023_03/story_24745/assets/2.jpeg?time=1677758242&size=*:900",
    title: "Realme GT",
    star: <AiFillStar className="rating-star" />,
    reviews: "Snapdragon",
    prevPrice: "$140,00",
    newPrice: "150",
    Size: "Android ",
    Native: "Long Battery Life",
    category: "Foldable Phones",
  },
  {
    id:11,
    img: "https://images.hindustantimes.com/img/2022/09/01/1600x900/2df2032a-29d6-11ed-bc83-9c2713d606c3_1662038669844.jpg",
    title: "iPhone 13 Pro Max",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "150",
    Size: "iPhone ",
    Native: "Dual SIM Support",
    category: "Foldable Phones",
  },
  {
    id:12,
    img: "https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/Galaxy_Z_Fold_3_render_6.208_4.jpg",
    title: "iPhone 13 Mini",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "150",
    Size: "iPhone ",
    Native: "Fast Charging",
    category: "Foldable Phones",
  },
  {
    id:13,
    img: "https://images-cdn.ubuy.co.in/653cd74c952cf47eac33d1c2-restored-apple-iphone-se-2nd-generation.jpg",
    title: "iPhone SE 2nd",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "150",
    Size: "iPhone ",
    Native: "Fast Charging",
    category: "Gaming Phones",
  },
  {
    id: 14,
    img: "https://techcrunch.com/wp-content/uploads/2019/04/DSCF5283.jpg",
    title: "iPhone 12 Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "150",
    Size: "iPhone ",
    Native: "Fast Charging",
    category: "Foldable Phones",
  },

  {
    id: 15,
    img: "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/618V2OyK53L.jpg",
    title: "iPhone 12",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "100",
    Size: "iPhone ",
    Native: "Wireless Charging",
    category: "Tablets",
  },
  {
    id: 16,
    img: "https://m.media-amazon.com/images/I/81LmL94PUvS.jpg",
    title: "iPhone 11 Pro Max",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "100",
    Size: "iPhone ",
    Native: "Wireless Charging",
    category: "Smartphones",
  },
  {
    id: 17,
    img: "https://www.gizmochina.com/wp-content/uploads/2023/01/huawei-1.png",
    title: "iPhone SE 1st",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "100",
    Size: "iPhone ",
    Native: "Wireless Charging",
    category: "Foldable Phones",
  },
  {
    id: 18,
    img: "https://www.smartcellular.in/media/catalog/product/cache/cfaa1692031f009488d1cfea5ce7e1ee/l/_/l_10185856_001_1_1.jpg",
    title: "iPhone XS Max",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "100",
    Size: "iPhone ",
    Native: "Dual SIM Support",
    category: "Gaming Phones",
  },
  {
    id: 19,
    img: "https://images-cdn.ubuy.co.in/64b044243a64a92126544120-tablets-10-inch-tablet-android-64gb-rom.jpg",
    title: "iPhone XR",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "100",
    Size: "iPhone ",
    Native: "Dual SIM Support",
    category: "Tablets",
  },
  {
    id: 20,
    img: "https://www.refurbished.store/cache/images/iphone-x-zilver-multiapple_1_600x600_BGresize_16777215-tj.png",
    title: "iPhone X",
    star: <AiFillStar className="rating-star" />,
    reviews: "A-series",
    prevPrice: "$140,00",
    newPrice: "50",
    Size: "iPhone ",
    Native: "Dual SIM Support",
    category: "Smartphones",
  },
];

export default data;
